title: Time Machine theme
description: Time Machine is a theme for GitHub Pages.
show_downloads: true
google_analytics: YOUR_GOOGLE_ANALYTICS_ID
theme: jekyll-theme-time-machine

collections:
  docs:
    output: true
    permalink: /:collection/:name/

gems:
  - jekyll-paginate

paginate: 5
paginate_path: "/page:num/"

permalink: /:categories/:year/:month/:day/:title/

